version: "1.0"

services:
    demand-database:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: rootUser
          MONGO_INITDB_ROOT_PASSWORD: rootPassword
        ports:
            - "27017:27017"
        container_name: demand-database
        networks:
            - foodtotem-network
    demand-api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "3001:80"
        environment:
            DemandDatabaseSettings__ConnectionString: mongodb://rootUser:rootPassword@demand-database:27017
        depends_on:
            - demand-database
        networks:
            - foodtotem-network
        restart: always
networks:
    foodtotem-network:
        driver: bridge

    
    