name: build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        continue-on-error: true
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.LAB_ACCOUNT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        continue-on-error: true
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        continue-on-error: true
        working-directory: ./infra/terraform
  
      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true
        working-directory: ./infra/terraform
        env:
          TF_VAR_lab_account_id: ${{ secrets.LAB_ACCOUNT_ID }}
          TF_VAR_lab_account_region: ${{ secrets.LAB_ACCOUNT_REGION }}
          TF_VAR_food_totem_demand_image: ${{ secrets.DEMAND_IMAGE }}
          TF_VAR_mongo_image: ${{ secrets.MONGO_IMAGE }}
          TF_VAR_mongo_root_password: ${{ secrets.MONGO_ROOT_PASSWORD }}
          TF_VAR_mongo_root_user: ${{ secrets.MONGO_USER }}
          TF_VAR_rabbitMQ_password: ${{ secrets.RABBITMQ_PASSWORD }}
          TF_VAR_rabbitMQ_user: ${{ secrets.RABBITMQ_USER }}